# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0002_auto_20180125_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(max_length=255),
        ),
    ]
